name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * 5'    # 每天运行一次
  workflow_dispatch:        # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Sync Fork
        uses: tgymnich/fork-sync@v1.8
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: wzdnzd
          base: main        # 原仓库的主分支名称
          head: main       # 您的fork仓库的主分支名称
